import os
import json
import argparse
from utils import evaluate_sop, evaluate_pp, evaluate_msp
from pathlib import Path

parser = argparse.ArgumentParser()
parser.add_argument('--type', default="msp_llama", type=str, help='Type of evaluation: sop_llama, sop_qwen, pp_llama, pp_qwen, msp_llama, msp_qwen')
args, _ = parser.parse_known_args()

"""
The preds folder contains the inference outputs for each task generated by our trained models. You may also retrain the models separately and run inference again if needed.
"""

if args.type == "sop_llama":
    answer_path = "./data/test_dataset_ver1.json"
    pred_path = f"./preds/sop_llama_ver1.jsonl"

elif args.type == "sop_qwen":
    answer_path = "./data/test_dataset_ver1.json"
    pred_path = f"./preds/sop_qwen_ver1.jsonl"

elif args.type == 'pp_llama':
    answer_path = "./data/test_dataset_ver1.json"
    pred_path = f"./preds/pp_llama_ver1.jsonl"

elif args.type == 'pp_qwen':
    answer_path = "./data/test_dataset_ver1.json"
    pred_path = f"./preds/pp_qwen_ver1.jsonl"

elif args.type == "msp_llama":
    answer_path = "./data/test_dataset_ver1.json"
    pred_path = f"./preds/msp_llama_ver1.jsonl"

elif args.type == "msp_qwen":
    answer_path = "./data/test_dataset_ver1.json"
    pred_path = f"./preds/msp_qwen_ver1.jsonl"



with open(answer_path, 'r', encoding='utf-8') as f:
    test_data = json.load(f) 

test_data_pred = []
with open(pred_path, "r", encoding="utf-8") as f:
    for line in f:
        if line.strip():
            test_data_pred.append(json.loads(line))

if args.type == "sop_llama" or args.type == "sop_qwen":
    test_data_pred = [item['predictions'] for item in test_data_pred]

    results = evaluate_sop(
        test_data,
        test_data_pred,
        reduced_formula=True
    )

    print(f"\n{args.type}_qlora_results: {results}")

    results_dir = Path("./results")
    results_dir.mkdir(parents=True, exist_ok=True)
    txt_path  = results_dir / f"Summary_{args.type}_results.txt"




elif args.type == "pp_llama" or args.type == "pp_qwen":

    test_data_pred = [item['predictions'] for item in test_data_pred]
    results = evaluate_pp(
        test_data, 
        test_data_pred,
        reduced_formula=True
    )
    print(f"{args.type}_qlora_results: {results}")


    results_dir = Path("./results")
    results_dir.mkdir(parents=True, exist_ok=True)
    txt_path  = results_dir / f"Summary_{args.type}_results.txt"


# Utilizing top-1 precursor predictions for MSP evaluation (inferenced precursor predictions)
elif args.type == "msp_llama" or args.type == "msp_qwen":
    test_data_pred = [item['predictions'] for item in test_data_pred]

    if args.type == "msp_llama":
        filtered_path = "./data/llama_ver1_selected_precs.json"
        with open(filtered_path, 'r', encoding='utf-8') as f:
            filtered_precs = json.load(f)

    if args.type == "msp_qwen":
        filtered_path = "./data/qwen_ver1_selected_precs.json"
        with open(filtered_path, 'r', encoding='utf-8') as f:
            filtered_precs = json.load(f) 

    results = evaluate_msp(test_data, test_data_pred, filtered_precs, reduced_formula=True)
    print(f"\n{args.type}_results: {results}")

    results_dir = Path("./results")
    results_dir.mkdir(parents=True, exist_ok=True)
    txt_path  = results_dir / f"Summary_{args.type}_results.txt"



with open(txt_path, "w", encoding="utf-8") as f:
    f.write(f"{args.type}_qlora_results: {results}\n")